### ISSUE TITLE
Add C# support

### ISSUE THREAD

**Issue by crertel** [medicalinformaticscorp/open-waveform-format#1]
We'd like to add C# support for OWF.

The API should:

* Allow creation of `x-owf+json` and `x-owf+binary` files
* Allow creation of channel objects, namespace objects, and signal and samples objects.
* Present a clean OO interface to above.
* Respect UTF8 encodings of strings
* Not throw exceptions during parsing

The API should not:
* assume a transport (though HTTP is expected, consumer of the API handle transport themselves)

**Comment by crertel** [comment]
For now, we're going to add support only for encoding/decoding the binary format.

**Comment by mjones-mic** [comment]
Closed by #3
