### ISSUE TITLE
Create C OWF testing server and C# OWF testing client

### ISSUE THREAD

**Issue by mjones-mic** [medicalinformaticscorp/open-waveform-format#18]
Let's get a simple client-server test up for OWF.

First, create a C# test client that will send OWF messages to a test server over TCP.

Then, make a C test server that will reply to those messages with more OWF (testing the client's encoding and decoding capabilities). The message should contain information on whether the OWF parsed successfully.

**Comment by cgrusin** [comment]
Please hold work on this until after the sprint planning meeting today.  It's priority has to be established relative to other objectives.

**Comment by crertel** [comment]
For this, I'd just go with the one-way C# to C over TCP, and stop. Basically, just enough to show that it works. Before starting on this, what time estimate do you have for how long it'd take?

**Comment by mjones-mic** [comment]
Probably just a day. Not hard stuff.

**Comment by crertel** [comment]
So, what's open on this right now?

Where are we at--what needs merging?

**Comment by mjones-mic** [comment]
Let's merge the C# and C stuff into development, because they're both at good stopping points. I'd consider the C# a good 0.9 release, because the API's fairly stable. I'd consider the C pretty close as well, but it still needs the generator.

**Comment by crertel** [comment]
Have we added ways of getting the API from those libraries?

**Comment by mjones-mic** [comment]
The C# library has 100% documentation coverage; the C library does not.

**Comment by crertel** [comment]
Sorry--meant *API version* not just *API*. My bad.

Something like `owf_get_version( &major, &minor, &patch);`

**Comment by mjones-mic** [comment]
Ahhh. Here's where I specified the assembly version in the C# API. Not sure if this is enough.

https://github.com/medicalinformaticscorp/open-waveform-format/blob/c-sharp-api/c-sharp/Properties/AssemblyInfo.cs#L49

Still need to do something equivalent in the C API, but I do have the `OWF_LIBRARY_VERSION` macro in `<owf/version.h>`:

https://github.com/medicalinformaticscorp/open-waveform-format/blob/feature-2/c/include/owf/version.h

So things like `#if OWF_LIBRARY_VERSION >= 0x1000` would work in practice.

**Comment by mjones-mic** [comment]
Everything covered by this issue is done.
