### ISSUE TITLE
C folder layout/API suggestions

### ISSUE THREAD

**Issue by mjones-mic** [medicalinformaticscorp/open-waveform-format#2]
# Folder layout

* Encoding/decoding
  * owf/binary.h: `owf_binary_writer_t` and `owf_binary_reader_t` structs holding state for binary encoding/decoding
  * owf/json.h: `owf_json_writer_t` and `owf_json_reader_t` structs holding state for JSON encoding/decoding
* Datatypes
  * owf/channel.h: `owf_channel_t` struct
  * owf/namespace.h: `owf_namespace_t` struct
  * owf/signal.h: `owf_signal_t` struct
  * owf/event.h: `owf_event_t` struct
  * owf/alarm.h: `owf_event_t` struct
  * owf/string.h: `owf_string_t` struct
  * owf/time.h: `owf_time_t` typedef/helpers

# API

Both the encoding and decoding APIs are designed to be highly stateful.

For encoding, the user pushes a series of pointers to objects onto the state, which are materialized to OWF or JSON in-place and sent to a `write` callback when a new chunk of data is ready to be written.

For decoding, the user registers a `read` callback that can retrieve a number of bytes from a user-defined data source. The user also registers callbacks for `channel`, `namespace`, `signal`, `event`, and `alarm`. Each of these callbacks is executed when the decoder encounters an object of a given type, and the user can return `true` or `false` from a callback to signal whether the decoder should continue processing that object's subtree.

Helpers would be available that would enable the materialization of entire OWF packets based on the visitor described above.

**Comment by crertel** [comment]
Some minor things:
* Consider putting all types in one header
* Make sure we include routines for doing safe arithmetic on the integer stuff
* Make sure that we allow users to specify their own allocators

**Comment by mjones-mic** [comment]
Pull #4 contains lots of work toward this.
