### ISSUE TITLE
OWF format changes for alarms

### ISSUE THREAD

**Issue by mjones-mic** [medicalinformaticscorp/open-waveform-format#7]
## Alarm (`owf_alarm_t`)

Alarm objects represent **alarm data containing a duration**. Alarms are ongoing events, and carry information about the duration of the alarm, as well as the alarm level.

```c
typedef struct owf_alarm {
    t64 t0, dt;
    u8 level, volume, _reserved_0, _reserved_1;
    owf_str_t type, data;
} owf_alarm_t;
```

|Type|Field|Description|
|:---|:----|:----------|
|`t64`|`t0`|The UNIX epoch timestamp at which this alarm happened, in 100ns intervals. Sample code for creating a suitable timestamp is provided below.|
|+ `t64`|`dt`|The duration for which this alarm has been ongoing, with 100ns precision.|
|+ `u8`|`level`|The level of the alarm. Levels are user-defined.|
|+ `u8`|`volume`|The volume (or "loudness") of the alarm. Volumes are user-defined.|
|+ `u8`|`_reserved_1`|Reserved to pad this field to 32 bits. Set to zero.|
|+ `u8`|`_reserved_2`|Reserved to pad this field to 32 bits. Set to zero.|
|+ `owf_string_t`|`type`|The type of the alarm, which can be interpreted by the application. **Note:** `owf_string_t` is variable-length.|
|`owf_string_t`|`data`|The message of the alarm, which can be interpreted by the application. **Note:** `owf_string_t` is variable-length.|

**Comment by crertel** [comment]
We want to ammend `id` here to be `message`, but otherwise this looks good.

**Comment by cgrusin** [comment]
Was just about to say that.

**Comment by mjones-mic** [comment]
I'm changing the examples, the ruby packet generator code, and the C unpacker. Will do a pull request for the generation code and examples, then merge the result into my working branch for the C unpacker so I can test against new data.

**Comment by mjones-mic** [comment]
Completed by #9 and #10.
